export const AUDIT_ACTIONS = {
  CATEGORY_CREATED: 'category.created',
  CATEGORY_UPDATED: 'category.updated',
  CATEGORY_ACTIVATED: 'category.activated',
  CATEGORY_DEACTIVATED: 'category.deactivated',
  CATEGORY_REORDERED: 'category.reordered',
  CATEGORY_DELETED: 'category.deleted',
  PRODUCT_CREATED: 'product.created',
  PRODUCT_UPDATED: 'product.updated',
  PRODUCT_PUBLISHED: 'product.published',
  PRODUCT_MOVED_TO_DRAFT: 'product.moved_to_draft',
  PRODUCT_ARCHIVED: 'product.archived',
  PRODUCT_DELETED: 'product.deleted',
  PRODUCT_VARIANT_CREATED: 'product_variant.created',
  PRODUCT_VARIANT_UPDATED: 'product_variant.updated',
  PRODUCT_VARIANT_ACTIVATED: 'product_variant.activated',
  PRODUCT_VARIANT_DEACTIVATED: 'product_variant.deactivated',
  PRODUCT_VARIANT_DEFAULT_CHANGED: 'product_variant.default_changed',
  PRODUCT_VARIANT_DELETED: 'product_variant.deleted',
  INVENTORY_RESTOCKED: 'inventory.restocked',
  INVENTORY_ADJUSTED: 'inventory.adjusted',
  INVENTORY_DAMAGED: 'inventory.damaged',
  AVAILABILITY_WINDOW_CREATED: 'availability_window.created',
  AVAILABILITY_WINDOW_UPDATED: 'availability_window.updated',
  AVAILABILITY_WINDOW_ACTIVATED: 'availability_window.activated',
  AVAILABILITY_WINDOW_DEACTIVATED: 'availability_window.deactivated',
  AVAILABILITY_WINDOW_DELETED: 'availability_window.deleted',
  AVAILABILITY_WINDOW_REORDERED: 'availability_window.reordered',
  PRODUCT_IMAGE_CREATED: 'product_image.created',
  PRODUCT_IMAGE_UPDATED: 'product_image.updated',
  PRODUCT_IMAGE_PRIMARY_CHANGED: 'product_image.primary_changed',
  PRODUCT_IMAGE_DELETED: 'product_image.deleted',
  PRODUCT_IMAGE_REORDERED: 'product_image.reordered',
  ORDER_CONFIRMED: 'order.confirmed',
  ORDER_PREPARING: 'order.preparing',
  ORDER_READY_FOR_PICKUP: 'order.ready_for_pickup',
  ORDER_COMPLETED: 'order.completed',
  ORDER_CANCELLED: 'order.cancelled',
  PAYMENT_CASH_RECEIVED: 'payment.cash_received',
} as const;
export const AUDIT_RESOURCE_TYPES = {
  CATEGORY: 'category',
  PRODUCT: 'product',
  PRODUCT_VARIANT: 'product_variant',
  INVENTORY: 'inventory',
  AVAILABILITY_WINDOW: 'availability_window',
  PRODUCT_IMAGE: 'product_image',
  ORDER: 'order',
} as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
export interface AuditContext {
  adminId: string;
  ipAddress?: string;
  userAgent?: string;
}
