import type { PrismaClient } from '../src/generated/prisma/client';

type Unit = 'GRAM' | 'KILOGRAM' | 'LITER' | 'PIECE';
type Row = readonly [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  Unit,
  string,
  string,
  boolean?,
];
const rows: Row[] = [
  [
    'Mladi kozji sir',
    'mladi-kozji-sir',
    'mlecni-proizvodi',
    'FARMA-SIR-MLADI',
    'Pakovanje 1 kg',
    '1250.00',
    '1.000',
    'KILOGRAM',
    '38.000',
    'mladi-kozji-sir.webp',
    true,
  ],
  [
    'Stari kozji sir',
    'stari-kozji-sir',
    'mlecni-proizvodi',
    'FARMA-SIR-STARI',
    'Pakovanje 300 g',
    '680.00',
    '300.000',
    'GRAM',
    '20.000',
    'stari-sir.webp',
    true,
  ],
  [
    'SveÃ…Â¾e kozje mleko',
    'sveze-kozje-mleko',
    'mlecni-proizvodi',
    'FARMA-MLEKO',
    'FlaÃ…Â¡a 1 l',
    '220.00',
    '1.000',
    'LITER',
    '112.000',
    'kozje-mleko.webp',
    true,
  ],
  [
    'SveÃ…Â¾a surutka',
    'sveza-surutka',
    'mlecni-proizvodi',
    'FARMA-SURUTKA',
    'FlaÃ…Â¡a 1 l',
    '120.00',
    '1.000',
    'LITER',
    '64.000',
    'surutka.webp',
    true,
  ],
  [
    'DomaÃ„â€¡e jabuke',
    'domace-jabuke',
    'voce',
    'FARMA-JABUKE',
    '1 kg',
    '180.00',
    '1.000',
    'KILOGRAM',
    '45.000',
    'jabuke.webp',
  ],
  [
    'DomaÃ„â€¡e kruÃ…Â¡ke',
    'domace-kruske',
    'voce',
    'FARMA-KRUSKE',
    '1 kg',
    '220.00',
    '1.000',
    'KILOGRAM',
    '35.000',
    'kruske.webp',
  ],
  [
    'Ã…Â ljive',
    'sljive',
    'voce',
    'FARMA-SLJIVE',
    '1 kg',
    '180.00',
    '1.000',
    'KILOGRAM',
    '40.000',
    'sljive.webp',
  ],
  [
    'Kajsije',
    'kajsije',
    'voce',
    'FARMA-KAJSIJE',
    '1 kg',
    '280.00',
    '1.000',
    'KILOGRAM',
    '25.000',
    'kajsije.webp',
  ],
  [
    'Maline',
    'maline',
    'voce',
    'FARMA-MALINE',
    'Pakovanje 125 g',
    '220.00',
    '125.000',
    'GRAM',
    '20.000',
    'maline.webp',
  ],
  [
    'Divlje kupine',
    'divlje-kupine',
    'voce',
    'FARMA-KUPINE-DIVLJE',
    'Pakovanje 125 g',
    '300.00',
    '125.000',
    'GRAM',
    '14.000',
    'kupine-divlje.webp',
  ],
  [
    'DomaÃ„â€¡e kupine',
    'domace-kupine',
    'voce',
    'FARMA-KUPINE-DOMACE',
    'Pakovanje 250 g',
    '280.00',
    '250.000',
    'GRAM',
    '18.000',
    'kupine-domace.webp',
  ],
  [
    'ViÃ…Â¡nje',
    'visnje',
    'voce',
    'FARMA-VISNJE',
    '1 kg',
    '260.00',
    '1.000',
    'KILOGRAM',
    '25.000',
    'visnje.webp',
  ],
  [
    'TreÃ…Â¡nje',
    'tresnje',
    'voce',
    'FARMA-TRESNJE',
    '1 kg',
    '350.00',
    '1.000',
    'KILOGRAM',
    '22.000',
    'tresnje.webp',
  ],
  [
    'Crvene ribizle',
    'crvene-ribizle',
    'voce',
    'FARMA-RIBIZLE',
    'Pakovanje 125 g',
    '250.00',
    '125.000',
    'GRAM',
    '16.000',
    'ribizle.webp',
  ],
  [
    'Paradajz',
    'paradajz',
    'povrce',
    'FARMA-PARADAJZ',
    '1 kg',
    '180.00',
    '1.000',
    'KILOGRAM',
    '42.000',
    'paradajz.webp',
  ],
  [
    'Krastavac',
    'krastavac',
    'povrce',
    'FARMA-KRASTAVAC',
    '1 kg',
    '150.00',
    '1.000',
    'KILOGRAM',
    '35.000',
    'krastavac.webp',
  ],
  [
    'Zelena salata',
    'zelena-salata',
    'povrce',
    'FARMA-SALATA',
    '1 glavica',
    '100.00',
    '1.000',
    'PIECE',
    '30.000',
    'zelena-salata.webp',
  ],
  [
    'Beli mladi luk',
    'beli-mladi-luk',
    'povrce',
    'FARMA-BELI-LUK',
    '1 veza',
    '80.00',
    '1.000',
    'PIECE',
    '32.000',
    'beli-mladi-luk.webp',
  ],
  [
    'Crni mladi luk',
    'crni-mladi-luk',
    'povrce',
    'FARMA-CRNI-LUK',
    '1 veza',
    '90.00',
    '1.000',
    'PIECE',
    '32.000',
    'crni-mladi-luk.webp',
  ],
  [
    'Zelje',
    'zelje',
    'povrce',
    'FARMA-ZELJE',
    '1 veza',
    '100.00',
    '1.000',
    'PIECE',
    '24.000',
    'zelje.webp',
  ],
  [
    'Blitva',
    'blitva',
    'povrce',
    'FARMA-BLITVA',
    '1 veza',
    '120.00',
    '1.000',
    'PIECE',
    '24.000',
    'blitva.webp',
  ],
  [
    'Loboda',
    'loboda',
    'povrce',
    'FARMA-LOBODA',
    '1 veza',
    '120.00',
    '1.000',
    'PIECE',
    '20.000',
    'loboda.webp',
  ],
  [
    'Komovica',
    'komovica',
    'rakija',
    'FARMA-KOMOVICA',
    'FlaÃ…Â¡a 0,7 l',
    '1200.00',
    '0.700',
    'LITER',
    '18.000',
    'rakija-komovica.webp',
  ],
  [
    'Ã…Â ljivovica',
    'sljivovica',
    'rakija',
    'FARMA-SLJIVOVICA',
    'FlaÃ…Â¡a 0,7 l',
    '1450.00',
    '0.700',
    'LITER',
    '20.000',
    'rakija-sljiva.webp',
  ],
  [
    'DunjevaÃ„Âa',
    'dunjevaca',
    'rakija',
    'FARMA-DUNJEVACA',
    'FlaÃ…Â¡a 0,7 l',
    '2600.00',
    '0.700',
    'LITER',
    '10.000',
    'rakija-dunja.webp',
  ],
  [
    'SveÃ…Â¾a domaÃ„â€¡a jaja',
    'domaca-jaja',
    'jaja',
    'FARMA-JAJA-10',
    'Pakovanje 10 komada',
    '300.00',
    '10.000',
    'PIECE',
    '86.000',
    'jaja.webp',
    true,
  ],
  [
    'Stajsko Ã„â€˜ubrivo',
    'stajsko-djubrivo',
    'stajsko-djubrivo',
    'FARMA-DJUBRIVO-20KG',
    'DÃ…Â¾ak 20 kg',
    '600.00',
    '20.000',
    'KILOGRAM',
    '30.000',
    'stajsko-djubrivo.webp',
  ],
];

export async function seedFarmCatalog(prisma: PrismaClient): Promise<number> {
  await prisma.productImage.deleteMany({
    where: {
      storageProvider: 'local-demo',
      storageKey: { startsWith: 'demo/' },
    },
  });
  for (const [
    name,
    slug,
    categorySlug,
    sku,
    variant,
    price,
    amount,
    unit,
    stock,
    image,
    featured = false,
  ] of rows) {
    const category = await prisma.category.findUniqueOrThrow({
      where: { slug: categorySlug },
    });
    const copy = {
      categoryId: category.id,
      name,
      shortDescription: `DomaÃ„â€¡i proizvod Borske Farmice: ${name}.`,
      description: `${name} iz lokalne ponude. Dostupnost i termin liÃ„Ânog preuzimanja potvrÃ„â€˜uje administrator.`,
      status: 'ACTIVE' as const,
      isFeatured: featured,
      isMainProduct: featured,
      availabilityMode: 'ALWAYS' as const,
      isManuallyAvailable: true,
    };
    const product = await prisma.product.upsert({
      where: { slug },
      update: copy,
      create: { ...copy, slug },
    });
    const variantData = {
      productId: product.id,
      name: variant,
      price,
      packageAmount: amount,
      measurementUnit: unit,
      stockQuantity: stock,
      lowStockThreshold: '3.000',
      minimumPurchaseQuantity: '1.000',
      purchaseIncrement: '1.000',
      isDefault: true,
      isActive: true,
    };
    await prisma.productVariant.upsert({
      where: { sku },
      update: variantData,
      create: { ...variantData, sku },
    });
    const storageKey = `farm-catalog/${image}`;
    const imageData = {
      productId: product.id,
      url: `/images/products/${image}`,
      width: 900,
      height: 900,
      format: 'webp',
      altText: `${name} Ã¢â‚¬â€ Borska Farmica`,
      isPrimary: true,
      sortOrder: 0,
    };
    await prisma.productImage.upsert({
      where: {
        storageProvider_storageKey: {
          storageProvider: 'local-demo',
          storageKey,
        },
      },
      update: imageData,
      create: { ...imageData, storageProvider: 'local-demo', storageKey },
    });
  }
  return rows.length;
}
